### PR TITLE
OSFUSE-507: Added JBoss Fuse kar to fabric8-project-bom-fuse

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dhirajsb** [comment]
ok to test

**Comment by dhirajsb** [comment]
ok to test

**Comment by dhirajsb** [comment]
Looks like this is not using Java 8??

**Comment by jimmidyson** [comment]
Looks like someone had screwed up all the different JDK versions on fabric8 slave configs... hopefully fixed up now.

ok to test

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
ok to test

**Pull request merged**
