### PR TITLE
OSFUSE-499: enable basic user to clean-up namespace/project created by Arquillian tests

### PR DESCRIPTION
**Pull request by astefanutti**

### CODE REVIEW

**Comment by davsclaus** [comment]
ok to test

**Comment by oscerd** [comment]
Merged here.

https://github.com/fabric8io/fabric8/commit/e7dffef943898777cb08adb2cb7732939d69d83e

**Comment by oscerd** [comment]
@astefanutti I guess you can close this one :-)

**Comment by astefanutti** [comment]
@oscerd @davsclaus thanks! Closing.

**Pull request closed without merging**
