### PR TITLE
Added logging for compile errors when using kubernetes-generator

### PR DESCRIPTION
**Pull request by garethahealy**
#5901 - Now prints out the diagnostics:

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Failed to compile provider classes. See output below.
[ERROR] Compile error: /Users/garethah/Documents/workspace/blah/src/main/java/com/blah/buildconfig/DeploymentConfigKubernetesModelProcessor.java:161: error: incompatible types: java.lang.Long cannot be converted to java.lang.Integer
          probe.setInitialDelaySeconds(new Long(15));

### CODE REVIEW

**Comment by davsclaus** [comment]
Looks good IMHO @iocanel any thoughts?

**Comment by rhuss** [comment]
LGTM, too. However I wonder where the empty commit 317cff8 comes from and whether we shouldn't squash the PR before merging to a single commit ? (just early sunday morning nit picking ;-)

**Comment by davsclaus** [comment]
Yeah @rhuss that sounds good.

github is adding a squash feature I saw on twitter.

**Comment by davsclaus** [comment]
@garethahealy I wonder if you can squash this PR as we want to avoid that bit merge from master in your PR. Or do a new PR and cherry pick from this branch to the new branch the 2 commits that adds this functionality

**Comment by garethahealy** [comment]
Have created a new PR.

**Pull request closed without merging**
