### PR TITLE
OSFUSE-322: KubernetesAssert::deployments fails if test project depends on more than 1 deployments

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by iocanel** [comment]
I am looking at it right now!

**Comment by iocanel** [comment]
Overall looks good!

I think there is a tiny little gap now that we no longer use the first pod. That gap could be possibly handled if we implemented something like:

    assertThat(client).deployments().pod("mypod")

... but given that when using deployments we don't have control over the pod name, that gets a little bit tricky.

So, let's merge.

**Comment by iocanel** [comment]
[merge]

**Comment by chirino** [comment]
Since the PR jobs is a little borked.. I'm going to manually merge for now.

**Pull request merged**
