### PR TITLE
Upgrade commons-codec to version 1.10

### PR DESCRIPTION
**Pull request by oscerd**
Hi,

This PR upgrades commons-codec to version 1.10.

Andrea

### CODE REVIEW

**Comment by davsclaus** [comment]
ok to test

**Comment by davsclaus** [comment]
there is a merge conflict, can you --rebase and update (you may need to do a --force)

**Comment by oscerd** [comment]
OK. I'll do the rebase in the afternoon.
Il 22/giu/2015 08:16, "Claus Ibsen" <notifications@github.com> ha scritto:

**Comment by oscerd** [comment]
Now it should be ok.

**Comment by oscerd** [comment]
Can you please amend the commit message "L" of the commit: https://github.com/fabric8io/fabric8/commit/46ed25d4667e4a0cc0131493dcb984b1370dca33 ?

I forget to close the rebase and I've pushed with a temporary commit message.

**Comment by davsclaus** [comment]
Ah that is okay ;)

**Pull request closed without merging**
