### PR TITLE
Upgrade Sundrio to version 0.0.24

### PR DESCRIPTION
**Pull request by oscerd**
Upgrade Sundrio to version 0.0.24.

Andrea

### CODE REVIEW

**Comment by jimmidyson** [comment]
@oscerd Do we even use this property in fabric8? Not sure we do any more do we?

**Comment by oscerd** [comment]
I see the dependency only in the pom.xml for the sundrio-maven-plugin. I think you're right.. We don't use it anymore.

**Comment by oscerd** [comment]
And the sundrio-maven-plugin block is commented.

**Comment by oscerd** [comment]
My mistake. Sorry. We can remove it.

**Comment by jimmidyson** [comment]
No need for sorry! Thanks for your help in keeping us up to date @oscerd.

**Pull request merged**
