### PR TITLE
10.245.* master and minion IP addresses changed in OpenShift vagrant

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by davsclaus** [comment]
@jimmidyson does this PR look okay?

**Comment by jimmidyson** [comment]
@davsclaus lgtm

ok to test

**Comment by jimmidyson** [comment]
ok to test

**Comment by davsclaus** [comment]
Thanks @ppalaga for the PR. Keep em coming ;)

**Comment by jimmidyson** [comment]
Merged as 5d35c97930a7ac9dc47e463b7a8b5408278ef961. Thanks @ppalaga

**Pull request closed without merging**
