### PR TITLE
Upgrade Lombok to version 1.16.4

### PR DESCRIPTION
**Pull request by oscerd**
This PR upgrades Lombok to version 1.16.4

Andrea

### CODE REVIEW

**Comment by davsclaus** [comment]
ok to test

**Comment by oscerd** [comment]
I'll investigate why

**Comment by oscerd** [comment]
Locally I don't have error..

**Comment by oscerd** [comment]
It was a connection timeout from the fusesource-ci server to maven.java.net..

```
[ERROR] Failed to execute goal on project rest-utils: Could not resolve dependencies for project io.fabric8:rest-utils:jar:2.3-SNAPSHOT: Failed to collect dependencies at org.eclipse.jetty:jetty-jsp:jar:9.1.5.v20140505 -> org.glassfish.web:javax.servlet.jsp:jar:2.3.2 -> org.glassfish:javax.el:jar:3.0.1-b07-SNAPSHOT: Failed to read artifact descriptor for org.glassfish:javax.el:jar:3.0.1-b07-SNAPSHOT: Could not transfer artifact org.glassfish:javax.el:pom:3.0.1-b07-SNAPSHOT from/to jvnet-nexus-snapshots (https://maven.java.net/content/repositories/snapshots): Connect to maven.java.net:443 [maven.java.net/207.223.241.86] failed: Connection timed out -> [Help 1]
```

Whenever you can we can retest :-)

**Comment by davsclaus** [comment]
ok to test

**Pull request closed without merging**
