### PR TITLE
Upgrade Jolokia to version 1.3.5

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by oscerd** [comment]
[merge]

**Comment by oscerd** [comment]
[merge]

**Comment by oscerd** [comment]
ok to test

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
[merge]

**Comment by oscerd** [comment]
Jenkins doesn't want to merge.

**Comment by jstrachan** [comment]
[merge]

**Comment by oscerd** [comment]
Weird

**Comment by jimmidyson** [comment]
This is merged already as 811cb611aa721c2e2a25170e8e0942349629daf5.

This repo has never, ever had the `[merge]` comment, it's always been merged by the default Jenkins build. That hasn't changed in forever.

**Comment by oscerd** [comment]
Sorry about this, I messed up with other repos in the organization.

**Comment by jimmidyson** [comment]
Don't be sorry! I want to change to the [merge] comment but don't want to affect other's workflow.

**Pull request closed without merging**
