### PR TITLE
Add new mojo plugin to create a Gerrit Git repo

### PR DESCRIPTION
**Pull request by cmoulliard**
Add new mojo plugin to create a Git repo under Gerrit Kube/Docker container. This plugin is required or at least the java code created (to be integrated later on with a more complete solution creation everything required for a CD/CI project) as the gerrit replicates git repo with gogs

Remar: There is still one thing to do as this PR contains DTO protected class. This code could be merged with what exist or we could create a Gerrit API to support the DTO & REST API

### CODE REVIEW

**Comment by davsclaus** [comment]
merged

**Comment by jimmidyson** [comment]
I'm not sure I like this mojo being part of the fabric8 maven plugin. Seems unrelated to the current plugin goals & too implementation dependent - we use Gerrit at the moment, but I assume users to use different solutions, Gerrit just being an OOTB one. Are we going to start adding Jenkins goals in? Gogs? Also I can't see any docs on how to use this or what you would use it for.

Wonder if we need a separate plugin for CI/CD stuff?

**Comment by davsclaus** [comment]
@jimmidyson +1

**Comment by cmoulliard** [comment]
If this change is too specific, this is also the case for the create gogs webhook mojo plugin.

**Comment by jimmidyson** [comment]
@cmoulliard Yes that is too :) I'd prefer a separate plugin for CD stuff.

**Pull request closed without merging**
