### PR TITLE
Revert "Rework apt profile that adds uneeded deps to all components, …

### PR DESCRIPTION
**Pull request by rawlingsj**
…to no-apt that explicitly disables annotation processing via "disable.annotation.processing" using properties."

Causing issue when performing release.

This reverts commit eab26094449bd1213a5d9d7ce58a044efafc02bc.

### CODE REVIEW

**Comment by iocanel** [comment]
[merge]

**Comment by jimmidyson** [comment]
@iocanel This is automerged ;)

**Comment by rawlingsj** [comment]
@jimmidyson it didn't automerge for some reason.

**Comment by iocanel** [comment]
Ha!

**Comment by jimmidyson** [comment]
I can see at the bottom of https://fabric8-ci.fusesource.com/job/fabric8-2.0-pullreq/1399/console that it did & was pushed.

**Pull request closed without merging**
