### PR TITLE
upgrade apiman and enable other "real" components

### PR DESCRIPTION
**Pull request by EricWittmann**
1) Upgraded apiman to 1.1.2.Preview2 (to avoid using snapshots)
2) Enable elasticsearch versions of API Gateway components such as the registry, rate limiter, and shared state service
3) Implemented apiman metrics using dropwizard metrics + JMS reporter

### CODE REVIEW

**Comment by davsclaus** [comment]
ok to test

**Comment by davsclaus** [comment]
Maybe the JAR is not yet synced to maven central, the CI server fails with

```
[ERROR] Failed to execute goal on project gateway-apiman: Could not resolve dependencies for project io.fabric8:gateway-apiman:jar:2.2-SNAPSHOT: The following artifacts could not be resolved: io.apiman:apiman-gateway-engine-core:jar:1.1.2.Preview2, io.apiman:apiman-gateway-engine-beans:jar:1.1.2.Preview2, io.apiman:apiman-gateway-engine-policies:jar:1.1.2.Preview2, io.apiman:apiman-gateway-api-rest:jar:1.1.2.Preview2, io.apiman:apiman-gateway-platforms-vertx:jar:1.1.2.Preview2: Could not find artifact io.apiman:apiman-gateway-engine-core:jar:1.1.2.Preview2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
```

**Comment by EricWittmann** [comment]
Yeah sorry about that - I didn't realize the JARs hadn't made their way to central yet.

**Comment by EricWittmann** [comment]
What's the appropriate next step once the JARs are available?  Submit a new PR?

**Comment by jimmidyson** [comment]
@EricWittmann - no we can just retest this

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
@EricWittmann - i assume they are synced now?

**Comment by EricWittmann** [comment]
Apparently not.  It's a mystery to me as to when the nexus->central sync happens.  I'll rerun it tomorrow am.

**Comment by davsclaus** [comment]
retest this please

**Comment by EricWittmann** [comment]
retest this please

**Comment by jimmidyson** [comment]
add to whitelist

**Comment by jimmidyson** [comment]
Merged.

**Pull request closed without merging**
