### PR TITLE
Harmonize environment variables in run script

### PR DESCRIPTION
**Pull request by rhuss**
As already discussed the syntax of the run scripts should be synchronized. 

The following was adapted, including fixes:

* Checked for consistency in naming (i.e. prefix JAVA_)
* Synced with variable names from fabric8/run-java
* Consolidated environment variables influencing java options
* Introduced local var convention to be lower case
* Added missing check for JAVA_CLASSPATH env
* Fixed bug because IFS  not reset
* Introduced a JAVA_DEBUG_PORT option
* Set line ending of .classpath from \r\n to \n
* Update readme.md

Further suggestions (not implemented)

* change ".classpath" to "classpath" to make it more visible (makes it easier to find when troubleshooting)
* change etc/default to run-env.sh, colocated to the run script. Also because of maintainability: it easier to find and correlate when it is colocated.

Where I'm a bit unsure is why the separator in the .classpath file was chosen to be `\r\n` instead of plain `\n` ? (should be feasible even on windows is fits better to the target environment which is unix anyway). Or why not simply already prepare the proper classpath (colon separated) when creating ?

### CODE REVIEW

**Comment by rhuss** [comment]
If there are no objections I'd like to apply that so that the quickstart changes in https://github.com/rhuss/ipaas-quickstarts/ can be applied for the change to hawt-app.

**Comment by jimmidyson** [comment]
@chirino Speak now or forever hold your peace.

LGTM.

**Comment by davsclaus** [comment]
I wonder if we can infer the run command when its an hawt-app
https://github.com/rhuss/ipaas-quickstarts/commit/e1a37f4afaa644679412f653f0db7afa3e53bf9a#diff-6cf82359a7b5152b8c66d693bec69da0R206

So the d-m-p do not have to specify that s2i run goal?

**Comment by davsclaus** [comment]
I guess a new d-m-p plugin is planned to be release fairly soon so its not SNAPSHOT

**Comment by davsclaus** [comment]
And for your suggestions.

+1 on classpath (having hidden files that make such a different is imho a bit bad, as you say much easier to trouble shoot if you can spot the file)

+1 on the run sctipt also easier to understand what the script does than having a plain named default.

+1 on line endings in unix style and colon separated.

**Comment by dhirajsb** [comment]
I don't se anything objectionable, agreed with claus on classpath, script names and unix conventions. The colon in path might become an issue if we ever have to support MS Windows.

**Comment by rhuss** [comment]
thanks !

/wrt to the classpath: This shouldn't be an issue currently since the run script itself will run on unix only anyway and the main focus is usage in a linux container (where it's ok, anyway). 

But agreed, when the hawt-app.tar is supposed to run flat on Windows with a (yet to write) run.bat, then it might be more difficult (but then you might need to replace `lib/bla.jar` to `lib\bla.jar` as well).

**Comment by rhuss** [comment]
@rawlingsj Super strange, this PR seems to be already applied on master (???). If you encounter some issues with mismatching version numbers lately, then it was my fault. I wanted to clean up the version numbers just after the last rebase before the PR gets applied (which I wanted to do now, but then I saw that the changes already appeared in master).

Sorry for any mess up ;(

**Comment by rawlingsj** [comment]
Ah no worries - I'll check it before kicking off a release, thanks for the heads up @rhuss

**Comment by rhuss** [comment]
Cool ;-) Just merged in my latest changes. I would be ready for a next release ;-)

**Pull request closed without merging**
