### PR TITLE
add support for specifying a node port from maven properties.

### PR DESCRIPTION
**Pull request by yongk802**
Allow node port(s) to be specified for a service from the maven pom.

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR. Do you mind add a row to the table for the json goal documentation in this file?
https://github.com/fabric8io/fabric8/blob/master/docs/mavenFabric8Json.md

Then we can include this new option in the documentation.

**Comment by yongk802** [comment]
Sure, no problem! I have updated the documentation as well. Thanks!

**Comment by davsclaus** [comment]
ok to test

**Comment by davsclaus** [comment]
thanks for the PR

**Pull request closed without merging**
