### PR TITLE
Update buildconfig webhooks URL to ..buildconfigs/{name}/webhooks

### PR DESCRIPTION
**Pull request by aslakknutsen**
Old URL cause 404 in OpenShift 0.6.0

### CODE REVIEW

**Comment by davsclaus** [comment]
@jimmidyson as we was on OS 0.5.x are would we be ready for OS 0.6.x ? There is 0.6.1 RC releases out.

And wouldn't the vagrant need to be updated ?

**Comment by jimmidyson** [comment]
@davsclaus Wait for #4192 then @aslakknutsen please rebase & repush.

**Comment by aslakknutsen** [comment]
rebase pushed

**Comment by jimmidyson** [comment]
ok to test

**Comment by aslakknutsen** [comment]
committed by Jenkins, but request remain open?

**Comment by jimmidyson** [comment]
Yeah close it. Committed under different sha so pr not auto closed.

**Pull request closed without merging**
