### PR TITLE
OSFUSE-507: Added JBoss Fuse kar to fabric8-project-bom-fuse

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dhirajsb** [comment]
ok to test

**Comment by dhirajsb** [comment]
ok to test

**Comment by dhirajsb** [comment]
Looks like this is not using Java 8??

**Comment by jimmidyson** [comment]
ok to test

**Comment by dhirajsb** [comment]
ok to test

**Comment by dhirajsb** [comment]
[merge] lgtm

**Pull request merged**
