### PR TITLE
add Bom for Cxf and Spring-Boot #6655

### PR DESCRIPTION
**Pull request by ffang**
(cherry picked from commit aff775777a220d8238c167cd1b61cbef802d5813)

### CODE REVIEW

**Comment by nicolaferraro** [comment]
ok to test

**Comment by rawlingsj** [comment]
add to whitelist

**Comment by ffang** [comment]
[merge]

**Comment by ffang** [comment]
ok to test

**Comment by rawlingsj** [comment]
ok to test

**Pull request closed without merging**
