### PR TITLE
OSFUSE-144: Creating a BOM for fabric8 jboss-fuse-* quickstarts

### PR DESCRIPTION
**Pull request by nicolaferraro**
Adding a fuse stack BOM with fabric8 and kubernetes-karaf dependencies.

### CODE REVIEW

**Comment by nicolaferraro** [comment]
@iocanel do you have time to check this?
Thanks

**Comment by iocanel** [comment]
add to whitelist

**Comment by iocanel** [comment]
There is one thing I am not sure about, should we have redhat version on master, or should we just limit those in the redhat branch. @davsclaus, @jstrachan wdyt?

**Comment by iocanel** [comment]
Just ignore me. We have redhat version in master already.

**Comment by iocanel** [comment]
[merge]

**Comment by davsclaus** [comment]
merged now

**Pull request closed without merging**
