### PR TITLE
Improve fabric8-karaf-cm

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by davsclaus** [comment]
ok to test

**Comment by davsclaus** [comment]
[merge]

**Comment by lburgazzoli** [comment]
@davsclaus looks like it has been merged but the pr nor closed, can I safely close it ?

**Comment by davsclaus** [comment]
Yeah sometimes PRs dont get closed, especially on this git repo. Others tend to close automatic.

**Pull request closed without merging**
