### PR TITLE
moved the forge rest-core over from the separate git repo so its included with the forge commands and built with the same version of forge and dependences as the rest of fabric8

### PR DESCRIPTION
**Pull request by jstrachan**
moved the forge rest-core over from the separate git repo so its included with the forge commands and built with the same version of forge and dependences as the rest of fabric8

### CODE REVIEW

**Comment by jstrachan** [comment]
retest this please jenkins

**Comment by kevinearls** [comment]
retest this please

**Comment by kevinearls** [comment]
retest this please

**Comment by jimmidyson** [comment]
Merged

**Pull request closed without merging**
